server:
  port: 8080
  servlet:
    context-path: /shipping

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: mainhathaodev@gmail.com
    password: ozxt lsot xsfe xcrv
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: "jdbc:mysql://localhost:3306/shipping"
    username: root
    password: root
  springdoc:
    api-docs:
      path: /v3/api-docs
    swagger-ui:
      path: /swagger-ui.html
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jpa.properties:
    javax:
      persistence:
        transaction:
          type: jta
